mafintosh/hyperdb

- test/helpers/create.js
- test/replicate.js
tests referenced 'hyperdb' instead of '..' or '../..'
> fix tests on v1.0.0

- example.js
I just noticed the difference of this particular detail because i was trying out the hypercore example minutes before.
> Fixes: Cannot find module 'hyperdb'

- README.md
- index.js
- package.json
- test/diff.js
- test/helpers/create.js
- test/replicate.js
An API that lets you compare the current state of a hyperdb to an earlier state. For example:
```js
var hyperdb = require('hyperdb')
var ram = require('random-access-memory')
var db = hyperdb(ram, {valueEncoding: 'json'})
db.put('/a/foo', 'quux', function (err) {
db.snapshot(function (err, at) {
db.put('/a/foo', 'baz', function (err) {
var rs = db.createDiffStream('/a', at)
rs.on('data', console.log)
})
})
})
```
outputs
```js
{ type: 'del', name: '/a/foo', value: 'baz' },
{ type: 'put', name: '/a/foo', value: 'quux' }
```
You can get a diff on any key prefix, much like `db.watch()`.
This also exposes another API function, `db.snapshot()`, which captures the feedID/seq tuples at the point in time that it's called. I'm not sure whether this is the optimal way to expose this (maybe …
> feature: db.createDiffStream()

- README.md
- index.js
- test/diff.js
- test/helpers/create.js
- test/history.js
Implements a `createHistoryStream` API. Nodes are produced from a readable stream in topographic sequence. That is, all nodes that a node is aware of via its `clock` are emitted before that node.
> API: db#createHistoryStream

- README.md
- index.js
- package.json
- test/basic.js
Hey @mafintosh and @noffle, this PR adds a simple interface for creating a writable stream. It simply pushes the data into the db's batch method. I have made it so that the it accepts both objects and arrays of objects. This adds a bit of complexity, but also adds flexibility so that we can write batches to the stream.
Let me know your thoughts.
> db.createWriteStream()

- package.json
This pr updates the dependency on `protocol-buffers` to ^4.0.2
The newest `protocol-buffers` version doesn't depend on `brfs@1.43`, which ultimately depends on [a vulnerable version of `static-eval` (@0.2.4) ](https://snyk.io/vuln/npm:static-eval:20171016).
ps: There's also [a pr on `brfs`](https://github.com/browserify/brfs/pull/84) to update it's dependencies.
---
full depencency graph:
`hyperdb@2.0.0 › protocol-buffers@3.2.1 › brfs@1.4.3 › static-module@1.5.0 › static-eval@0.2.4`
> update protocol-buffers to ^4.0.2

- index.js
- test/history.js
This addresses the following situation:
1. A hyperdb is created (A); it authorizes a new feed (B)
2. A live history stream is created on B (no entries written yet) *and* B writes its first entry
3. The `writer` event will fire first
4. The `writer` event handler in `createHistoryStream` turns off event listeners and does an async call to lookup the new head node
5. During this async period `append` fires, but is lost because step 4 turned it off
6. The history stream hangs indefinitely, waiting for an `append` event that never comes
> Fix race condition with history stream on auth'd feed

- index.js
- test/auth.js
1. always recognize the original db author as authorized
2. recognize others as authorized when the only head is by the author in question
> Handle edge cases in 'authorized'

- index.js
- test/basic.js
Allow to pass in a precreated key pair and store the secret key with the source feed. This allows to first create the key pair and then the hyperdb - useful e.g. if you want to manage many hyperdb and store them in dirs named after the pubkeys (otherwise you'd have to move the db after creation because you'd only know the pubkey after creation).
> Add option to pass in secret key

- index.js
- test/reopen-and-write.js
Entries written after re-opening were corrupt if additional writers
had be authorized (inflate was reset to zero).
> Restore ._feeds after re-opening database

- index.js
- test/corruption.js
I've had a few feeds that would no longer replicate because the
inflate field was reset to 'zero' after a few feeds have been
authorized.
This check will create a new error 'Missing feed mappings' if
an entry has a clock that has a different number of feeds than
the mappings generated from the head's feedsMessage.
> Add new error check and test for corruption on inflate field

- lib/watch.js
I was getting an exception:
/app/node_modules/hyperdb/lib/watch.js:63
if (err) return this._destroy(err)
^
TypeError: this._destroy is not a function
at Watcher.onkick (/app/node_modules/hyperdb/lib/watch.js:63:24)
> Rename call to non-existent ._destroy() method to .destroy()

- index.js
- test/watch.js
Added a .watch() test for a 3 writer scenario where the third
writer joins after the .watch() is started.
Update the logic for _maybeUpdateFeeds to avoid 'Missing feed mappings'
assertions.
> Replication fixes with 3 writers

- lib/iterator.js
- test/iterator-order.js
By reversing the sort order in iterator, we can efficiently iterate over results in descending hash order. This option will be necessary for a leveldown implementation. Implements #107 
This PR:
1. Adds the `reverse` option to iterator
2. Duplicates the tests in `iterator-order.js` to test for reverse iteration.
> Add reverse option to iterator

- index.js
- lib/get.js
- lib/iterator.js
- lib/messages.js
- lib/put.js
- schema.proto
- test/corruption.js
- test/deletes.js
Backwards compat. Should make it possible to delete with a value which is useful for resolving conflicts
> add node.deleted to indicate if a node is deleted

- index.js
Since we added the protocol header it's a bit easier to reason about. This makes operations wait if no data has been written to the source feed or your local feed.
> cleanup waitForUpdate

- index.js
- lib/put.js
- test/basic.js
With the change in https://github.com/mafintosh/hyperdb/pull/122, deletes are no longer represented by a `null` value, meaning nodes can have arbitrary values and still be considered deletions.
This PR makes `null` an acceptable value for `put`/`get`.
Summary of changes:
1. Added options to `put`, so that you can mark a given put as a delete (`del` calls `put` under the hood).
2. Added a test for putting/getting a non-deleted node with a `null` value.
> Support for putting/getting null values

- README.md
I was checking if the `reverse` option was already implemented in `./lib/iterator`, because I might need it for a project I'm working on. Turns out it is, so this patch adds this information to the API documentation for `createReadStream`.
I'm wondering though whether reading records in reverse order will affect performance, like it does in LevelDB. If thats the case I could add another line to the documentation to point that out.
> Document `createReadStream` reverse

- index.js
batching doesn't normalize the key before calling put, and this leads to [isPrefix()](https://github.com/doraemondrian/hyperdb/blob/master/lib/iterator.js#L232) to return false later, resulting in `null` results for queries.
> batch needs to normlize key

- README.md
- index.js
- lib/get.js
- lib/key-history.js
- test/key-history.js
This is a simple PR to add the ability to stream the history of a specific prefix.
I want to be able to quickly iterate all values that a key has ever been.
I have write basic tests and it appears to be working, but I wanted to get your thoughts on this @mafintosh, to see if I am approaching the problem in the best way - or if there is a smarter way of traversing backwards.
> Add key history iterator

- index.js
- test/basic.js
- test/replicate.js
Some users may re-use the opts object passed as a parameter,
which results in surprising behaviour protocol errors after multiple
calls to .replicate() eg. random errors such as:
Only 128 feeds currently supported.
Remote sent invalid feed message
Remote message is larger than 8MB (max allowed)
There was also an instance of the opts object in the constructor
being mutated as well, so added an Object.assign for that as well.
> Use Object.assign to ensure opts isn't mutated

- test/read-stream.js
Just adding @noffle's test case to the createReadStream tests.
It looks like its working ok, so this PR could close #134.
> add empty test case for createReadStream

- lib/iterator.js
- test/iterator.js
This pr adds the delete option, which is available in the `get` method, to the `createReadStream` and `iterator` methods.
My main motivation for this change is so that I can see all values that have been added to the database regardless of whether they still exist or not. 
I need this functionality for [hyperdb-stage](https://github.com/e-e-e/hyperdb-stage) so that I can easily merge staged deletions. This PR will fix this currently broken test - https://github.com/e-e-e/hyperdb-stage/blob/master/test/staged.test.js#L174-L184
> add deletes option to iterator

- lib/put.js
- test/basic.js
For certain use-cases (particularly when keys are content-hashes of values), it'd be nice to be able to combine an existence check + the insertion into one operation. When the `ifNotExists` flag is set in `put`, the insertion will stop if it detects that the closest node has the same key as the one being inserted. With this approach, only one traversal is required to accomplish the above workflow.
The PR:
1. Adds the `ifNotExists` flag to `db.put`
2. Adds three tests (in `test/basic.js`) to ensure that this behavior works correctly (including in the presence of conflicts).
> Added ifNotExists option to put
